-- =====================================================================
-- Vokes POC — schema
-- Run this FIRST in the Supabase SQL editor (Dashboard → SQL Editor → New query)
-- =====================================================================
-- This models the FULL Airtable structure, including the fields that are
-- missing from the current CSV exports. Those columns simply load as NULL,
-- which is deliberate: it shows the admin that nothing is designed out.

drop view if exists player_stats, head_to_head, season_stats, match_detail cascade;
drop table if exists performances, matches, players, oppositions, seasons cascade;

-- ---------------------------------------------------------------- lookups
-- NB: identity columns, so the seed can supply explicit ids AND the live forms
-- can insert without one. 03_after_load.sql resets the sequences afterwards.

create table seasons (
  id    int generated by default as identity primary key,
  name  text not null unique
);

create table oppositions (
  id    int generated by default as identity primary key,
  name  text not null unique
);

create table players (
  id         int generated by default as identity primary key,
  name       text not null unique,
  photo_url  text,                       -- Airtable player photo
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- matches
create table matches (
  id                   int generated by default as identity primary key,
  fixture_name         text not null unique,
  opposition_id        int  not null references oppositions(id),
  season_id            int  references seasons(id),
  played_on            date,
  goals_for            int,
  goals_against        int,
  result               text check (result in ('Win','Draw','Loss')),
  opponent_has_keeper  boolean,          -- from "Create a new match" form
  one_where            text,             -- "The one where…"
  notes                text,
  weather              text,
  match_report         text,
  motm_player_id       int references players(id),
  dotd_player_id       int references players(id),
  created_at           timestamptz not null default now()
);

create index on matches (played_on desc);
create index on matches (opposition_id);
create index on matches (season_id);

-- ----------------------------------------------------------- performances
create table performances (
  id                 bigint generated by default as identity primary key,
  match_id           int not null references matches(id) on delete cascade,
  player_id          int not null references players(id),
  goals              numeric,
  penalties          numeric,
  assists            numeric,
  errors             numeric,            -- errors leading to goals
  pints              numeric,
  shots_out_of_cage  numeric,
  xg_for             numeric,            -- expected goals for
  xg_against         numeric,            -- expected goals against
  spice_rating       int check (spice_rating between 1 and 5),
  clean_sheet        boolean,            -- null = N/A (wasn't in goal)
  disciplinary       text check (disciplinary in
                       ('Not for me','Just a warning 😇','2 minutes in the bin','Naughty step')),
  game_description   text,
  memorable_moment   text,
  paid               text check (paid in
                       ('Yes I''ve already paid','No I''m a bad bloke and will pay now','Unknown')),
  created_at         timestamptz not null default now(),
  -- one submission per player per match (this is what the 8 Airtable
  -- duplicates violated — the database now prevents a repeat)
  unique (match_id, player_id)
);

create index on performances (player_id);
create index on performances (match_id);

-- ------------------------------------------------------------------- RLS
-- POC posture: the world can read, and can submit a performance or create a
-- match (exactly what the current public Airtable forms allow). Nothing can
-- be edited or deleted without the service key.

alter table seasons      enable row level security;
alter table oppositions  enable row level security;
alter table players      enable row level security;
alter table matches      enable row level security;
alter table performances enable row level security;

create policy read_seasons      on seasons      for select using (true);
create policy read_oppositions  on oppositions  for select using (true);
create policy read_players      on players      for select using (true);
create policy read_matches      on matches      for select using (true);
create policy read_performances on performances for select using (true);

create policy submit_performance on performances for insert with check (true);
create policy create_match       on matches      for insert with check (true);

-- Deliberately NO update/delete policies: the form can add, never destroy.
-- Five years of history cannot be damaged through the public site.
